name: speech_to_text_app
description: A Flutter app for speech-to-text and translation.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '^3.6.0'

dependencies:
  flutter:
    sdk: flutter
  speech_to_text: ^7.0.0
  translator: ^1.0.3+1 # Use the latest version of the translator package
  flutter_tts: ^4.2.1
  http: ^1.2.2

  flutter_dotenv: ^5.2.1
  whisper_dart: ^0.0.11
  flutter_native_splash: ^2.4.4
  flutter_spinkit: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png

flutter_native_splash:
  color: "#6200EE" # Background color of the splash screen
  image: assets/logo.png # Path to your splash screen logo
  android: true
  ios: true
  web: true
  fullscreen: true
